# html lang
language: zh-CN

# main menu navigation
menu:
  Home: /index.html
  Archives: /archives/index.html
  Reading: /reading/index.html
  About: /about/index.html

site:
  # banner: /img/banner.jpg # banner map of website. (please annotation this line if you don't need it)
  avatar: /images/head_pic.jpg # head portrait.
  #icp: xxxxxx # E-ICP prepared No.

# stylesheets loaded in the <head>
stylesheets:
  - /css/markdown.css
  - /css/july.css

# scripts loaded in the end of the body
scripts:
  - /js/jquery-3.4.1.min.js
  - /js/highlight-9.13.1.min.js
  - /js/transition.js
  - /js/smooth-scroll.min.js

hljs:
  enable: false # true to enable the plugin
  line_number: false # add line_number in frontend or backend (not recommend, have bugs in special hexo version)
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: true # show copy code in caption.
  label:
    left: Code
    right: ':'
    copy: Copy Code

# atom: atom.xml # website feed.

# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/


gitalk:
  enable: post
  on: true
  owner: zs1621
  repo: dadoudou.me
  admin: ['zs1621']
  accessToken: 997eb7f03bafcfef0d6b3030543c5a6e903fb771
  clientID: 01408711d79d72f03315
  clientSecret: 238abe81d923c8392d36e3cdb14d29961f1870b2
  labels: ['Gitalk']
